schema_version: 1

context:
  name: composio-openai
  version: "0.17.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/composio_openai-${{ version }}.tar.gz
  sha256: 9372ff957d5b4eb0ff0ef0bc36fa5aba6a423f2128f3b5354697a5b82bf5864c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0
    - openai
    - composio

tests:
  - python:
      imports:
        - composio_openai
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: Use Composio to get an array of tools with your OpenAI Function Call.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/ComposioHQ/composio

extra:
  recipe-maintainers:
    - jan-janssen
