schema_version: 1

context:
  name: composio-openai
  version: "0.22.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/composio_openai-${{ version }}.tar.gz
  sha256: 5d90e0f2a97ba34ad33204b36c364f0caf076b5ef1a8f2af47e4bf8aeab758f6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }},<4.0
    - openai
    - composio

tests:
  - python:
      imports:
        - composio_openai
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: Use Composio to get an array of tools with your OpenAI Function Call.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/ComposioHQ/composio

extra:
  recipe-maintainers:
    - jan-janssen
